dist: bionic # https://docs.travis-ci.com/user/reference/bionic/
language: java

cache:
  directories:
    - '$HOME/.m2/repository'

jdk: # https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
  - openjdk9
  - openjdk16
  
env:
  - TRAVIS_TAG=00.01 # see https://docs.travis-ci.com/user/environment-variables/
install: true # Without that statement, Travis will run 'mvn install' on pom.xml before the script step.

script: 
  - hostname
  - whoami
  - mvn --batch-mode -f pom.xml clean package
  - ls -la target

after_script:  
  - echo "TRAVIS_TAG = ${TRAVIS_TAG}"

deploy: # see https://docs.travis-ci.com/user/deployment/releases/ 
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: target/getdown-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    branch: getdown-1.5.1 # see https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
   
